import About from "../components/About Section/About";
import Head from 'next/head';
import Team from "../components/About Section/Team";
import ContactUs from "../components/ContactUs";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Service from "../components/Service";
import Meta from "../components/utils/meta";

export default function Home() {
  return (
    <>
    <Meta title="BAAF | Financial Stewardship with Ethical Vision"/>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    <Navbar/>
     <Hero/>
     <Service/>
     <About/>
     <Team/>
     <ContactUs/>
     <Footer/>
    </>
  );
}
